apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sanjib1984
  namespace: demo
spec:
  selector:
    matchLabels:
      app: sanjib1984
  template:
    metadata:
      labels:
        app: sanjib1984
    spec:
      containers:
        - name: sanjib1984
          image: sanjib1984/scrum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
